version: '3'

services:

  orch:
    build: 
      context: ../../../
      dockerfile: delivery/docker/dev/Dockerfile
    volumes:
      - ../../../:/home/contint/go/src/pdihub.hi.inet/awazza/niji-orchestrator
    ports:
      - 9000:9000
    user: contint
    entrypoint: delivery/docker/dev/entrypoint.sh
    command: make run
