version: '3'

services:

  odor:
    build: 
      context: ../../../
      dockerfile: delivery/docker/dev/Dockerfile
    volumes:
      - ../../../:/root/go/src/github.com/jlorgal/odor
    ports:
      - 9000:9000
    #command: make run
    command: sleep 1000
